version: '3.8'

services:
  dokku:
    container_name: dokku
    restart: unless-stopped
    # image: dokku/dokku:0.30.1
    build:
      context: .
      # install pack in Dockerfile
      dockerfile: Dockerfile
    ports:
      - '3022:22'
      # ports must be free
      - '443:443'
      - '80:80'
    environment:
      - DOKKU_HOSTNAME=dokku.${SERVER_HOSTNAME}
      - DOKKU_HOST_ROOT=${PWD}/dokku-data/home/dokku
    volumes:
      - ${PWD}/dokku-data:/mnt/dokku
      - ${PWD}/plugin-list:/mnt/dokku/plugin-list
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dokku-external

  portainer-standalone:
    image: 'portainer/portainer-ce:2.17.0'
    container_name: portainer-standalone
    restart: unless-stopped
    # open firewall
    ports:
      - '9443:9443'
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    networks:
      - default

networks:
  dokku-external:
    external: true
  default:
    name: portainer-standalone
